"""init

Revision ID: a59e69469894
Revises:
Create Date: 2024-08-30 15:27:44.137435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a59e69469894'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updatepoints', sa.Column('type', sa.Enum('NEW', 'IMPROVED', 'FIXED', 'UPDATED', 'DEPRECATED', 'REMOVED', name='updatepointtype'), nullable=False))
    op.alter_column('updatepoints', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('updates', sa.Column('product_id', sa.Integer(), nullable=False))
    op.alter_column('updates', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('IN_PROGRESS', 'IN_REVIEW', 'SHIPPED', 'DEPRECATED', name='updatestatus'),
               existing_nullable=False)
    op.create_foreign_key(None, 'updates', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.alter_column('updates', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'IN_REVIEW', 'SHIPPED', 'DEPRECATED', name='updatestatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('updates', 'product_id')
    op.alter_column('updatepoints', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('updatepoints', 'type')
    # ### end Alembic commands ###
